# local phase에서는 h2-database를 사용합니다.
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-admin-password: 1234

    datasource:
      url: jdbc:h2:~/test
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver