spring:
  application:
    name: SingSongSangSong

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22E206?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: S10P22E206
      password: CuSfPXDNXr
  data:
    mongodb:
      uri: mongodb+srv://S10P22E206:rui4ZhwEt1@ssafy.ngivl.mongodb.net/S10P22E206?authSource=admin
  #    mongodb:
##      uri: mongodb+srv://S10P22E206:rui4ZhwEt1@ssafy.ngivl.mongodb.net/S10P22E206?authSource=admin
#      host: S10P22E206:rui4ZhwEt1@ssafy.ngivl.mongodb.net
#      database: S10P22E206
#      authentication-database: admin
#      username: S10P22E206
#      password: rui4ZhwEt1
#      port: 27017
