spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/singsongsangsong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234

logging:
  level:
    org:
      springframework:
        security: trace